### ISSUE TITLE
Пересчёт TodaySpent при зачислении. 

### ISSUE THREAD

**Issue by SunSual** [money-check/MoneyCheckWebApp#55]
https://github.com/money-check/MoneyCheckWebApp/blob/2ed4835d68904d0352bfd1f3789b081179e45085/MoneyCheckWebApp/Controllers/WebExtensionsController.cs#L41

Лучше использовать фильтрацию по негативному значению.

**Comment by DenVot** [comment]
Перепроверяй свой код и вспомни про спецификацию 😉
