### ISSUE TITLE
Не округляется прогноз

### ISSUE THREAD

**Issue by Reworp** [money-check/MoneyCheckWebApp#63]
![image](https://user-images.githubusercontent.com/69410856/152137262-5d1eb3fa-c460-4c4f-a1ad-7d73d016f246.png)

**Comment by DenVot** [comment]
Добавить округление коде

https://github.com/money-check/MoneyCheckWebApp/blob/master/MoneyCheckWebApp/PricePredicating/PredicationProcessor.cs#L44
